# Generated by Django 5.1.3 on 2024-12-19 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='applicationandrating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(blank=True, max_length=30, null=True)),
                ('review', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
    ]
