# Generated by Django 5.1.3 on 2024-12-19 10:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0002_applicationandrating'),
    ]

    operations = [
        migrations.AddField(
            model_name='councellor',
            name='LOGINID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administrator.logintable'),
        ),
    ]
