# Generated by Django 5.1.3 on 2024-11-18 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('councellor', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='councellor',
            old_name='district',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='councellor',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='councellor',
            name='lastname',
        ),
        migrations.RemoveField(
            model_name='councellor',
            name='pin',
        ),
        migrations.RemoveField(
            model_name='councellor',
            name='place',
        ),
        migrations.RemoveField(
            model_name='councellor',
            name='state',
        ),
    ]
