# Generated by Django 5.1.3 on 2024-11-18 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('councellor', '0004_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='userid',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
