# Generated by Django 5.1.3 on 2024-11-18 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('councellor', '0005_alter_rating_userid'),
    ]

    operations = [
        migrations.CreateModel(
            name='complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(blank=True, max_length=30, null=True)),
                ('compalint', models.CharField(blank=True, max_length=100, null=True)),
                ('replay', models.CharField(blank=True, max_length=100, null=True)),
                ('complaintdate', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
