# Generated by Django 5.1.3 on 2024-11-18 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('councellor', '0006_complaint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='complaintdate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
